// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxzwbpfgvwuvcomuadoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4endicGZndnd1dmNvbXVhZG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzYzMjIsImV4cCI6MjA2NTQ1MjMyMn0.tH9cPGz1_fwy_uXcgs8qJf8BZ6BSYMC5zfl5tOs80BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);